import json

updates = {
    "restored_deep_8d886840": "As Republicans push a sweeping election-law strategy through the courts and Congress, voting rules are shifting late in the cycle. This raises the risk of disruption, mistrust, and fresh legal chaos ahead of the midterms. In a recent case before the Supreme Court, the conservative majority seemed sympathetic to the Republican National Committee's demand to bar certain state laws. These laws currently validate mail-in ballots postmarked but not received by officials on Election Day. If the RNC's argument proves successful, millions of Americans accustomed to voting by mail will need to learn new rules before this fall's midterms.\n\nCurrently, Texas and 13 other states allow postmarked ballots to be counted, even if they are only received by couriers on Election Day. Furthermore, 29 states offer that same privilege to military and overseas voters. These established rules could be abruptly terminated by the impending court ruling. Election experts warn that any of these kinds of policy changes are always borne by local election officials who are already stretched thin. If states are forced to change these deadlines before the fall, it will demand a remarkably tight turnaround.\n\nThis case is just one of hundreds of lawsuits being litigated that could alter how the upcoming election is administered. The RNC has focused significant time and resources on challenging American election laws to make the system more secure. Their stated goal is to restore voter faith in the electoral process and push the judiciary to clarify contradicting election laws. However, recent primary elections in Texas highlighted how last-minute changes can disenfranchise voters who turn up to the wrong place or at the wrong time. This confusion could be a mere taste of what is to come in November as these legal battles continue to unfold.",

    "restored_deep_8dccecdf": "The term 'K-shaped economy' is increasingly used by economists to describe a two-lane financial scenario. While some sectors experience rapid growth and recovery, others face continuous decline and stagnation. In this environment, everyday costs like groceries and car maintenance have surged significantly. This economic divide creates widespread frustration and anxiety among the general public. Consequently, these financial pressures can inadvertently make societies more vulnerable to political instability.\n\nSome historians draw parallels between current political climates and the gradual rise of autocratic regimes in the past. They note that assaults on the rule of law and morality are often incremental rather than immediate. When political norms are repeatedly crossed without consequence, the public can slowly adapt and normalize outrageous behavior. This phenomenon is described as sleepwalking into autocracy through a collective form of self-deception. Unless citizens remain vigilant and actively resist these power grabs, democratic institutions may steadily erode.\n\nSimultaneously, public health experts are warning about a growing antiscience crusade that threatens vulnerable populations. Older adults are particularly at risk as common infections can easily cascade into severe illnesses or death. Routine adult immunizations against diseases like shingles, the flu, and RSV remain crucial for maintaining long-term health. Recent studies even suggest that vaccines provide marvelous side effects, such as reducing the risk of dementia. Therefore, combating medical misinformation is just as vital as protecting democratic values in these challenging times.",

    "restored_deep_8d766319": "In a recent interview, Dave Grohl candidly discussed his addiction to achievement and his ongoing search for personal balance. Following a challenging period that included a public infidelity revelation, the musician has spent over 70 weeks in therapy. Grohl admitted that he used to keep his feelings trapped in his head instead of processing them through his heart. He realized he needed to stop, turn everything off, and fundamentally re-evaluate himself. This intense period of self-reflection has provided him with a new existential perspective on his life and career.\n\nBandmates have noticed a significant change in Grohl since he began prioritizing his mental health. He is now placing his aspirations for the band in a different context, giving more prominence to life outside of music. When the news of his personal struggles broke, the Foo Fighters paused their activities and canceled a planned tour. Despite the potential damage to the band's reputation, his bandmates rallied around him with unwavering support. They recognized that personal healing had to take precedence over their professional obligations.\n\nGrohl also reflected on the conflicting emotions he experiences regarding survival and loss in the music industry. After recently bumping into a former drug dealer who is now healthy and sober, he felt a mix of profound gratitude and devastating anger. This encounter forced him to confront his own survivor's guilt, especially considering the tragic loss of his former Nirvana bandmate, Kurt Cobain. Through therapy, Grohl is learning to navigate these complex feelings and understand that everyone is going through unseen struggles. Ultimately, he is committed to doing the necessary work to reach a place where he feels truly whole.",

    "restored_deep_8b369379": "Sri Lanka is currently grappling with a fragile recovery after suffering its worst economic crisis and the devastating impact of Cyclone Ditwah. Just as the island nation was beginning to stabilize from a protracted civil war and financial ruin, the severe storm displaced over 100,000 people. This natural disaster marked the first significant test for Anura Kumara Dissanayake, a newly elected president leading a coalition of previously inexperienced politicians. Despite the storm's severity, the government has proven to be a surprisingly responsible handler of the country's debts and recovery efforts. However, the combined economic and environmental blows have left lasting marks on the vulnerable nation.\n\nThe immediate response to Cyclone Ditwah was marred by chaotic coordination and communication failures. Despite prior warnings, some towns and villages received no alert, and it took over a week for medical supplies to reach remote areas. These missteps contributed to a death toll surpassing 800 people, though this figure was lower than previous disasters like the 2004 tsunami. The physical damage was extensive, with bridges, power stations, and buildings destroyed by flooding and massive landslides. Current estimates suggest the disaster caused asset losses equating to roughly 3.5% of the country's GDP.\n\nIn the aftermath, the recovery phase has shown more promise as roads and railways were quickly reopened. Traditional Western donors provided limited assistance, highlighting a shift in international disaster relief dynamics. Instead, regional powers like India and the UAE stepped in to provide crucial manpower, equipment, and substantial financial aid. The Dissanayake administration, despite its Marxist roots, has surprised many by leaning towards India and adhering to strict IMF fiscal discipline. While the government remains popular for curbing inflation and rebuilding reserves, the long-term path to development remains precarious due to rising poverty and stagnant incomes.",

    "restored_deep_880be766": "Although no bombs or missiles are falling on India, the ongoing conflict in the Persian Gulf is heavily impacting its economy. The war has exacerbated existing financial vulnerabilities, effectively kicking India when it is already down. Despite recent attempts to stimulate the market, experts warn that the current pickup in credit growth is completely unsustainable. Consequently, the value of the rupee continues to plummet as investor confidence rapidly deteriorates.\n\nThis economic uncertainty has prompted foreign portfolio investors to withdraw substantial amounts of capital from the country. The lack of foreign investment further weakens the rupee and complicates India's economic recovery. In stark contrast, some international corporate executives view the broader market dips as an opportunity. For example, top executives at firms like KKR have been steadily purchasing their own company's beleaguered stock. They argue that these strategic purchases reflect strong confidence in their long-term future performance.\n\nHowever, the ripple effects of the geopolitical conflict continue to dominate the financial landscape. Market volatility has led to significant shifts in asset management strategies across various sectors. Some activist investors are aggressively increasing their stakes in promising biotechnology and data software companies. Meanwhile, others are reducing their holdings in software providers to minimize their risk exposure. Ultimately, the interconnected nature of global markets means that regional wars can trigger widespread economic restructuring.",

    "restored_deep_8b39669b": "In his book 'The Coming Storm: Power, Conflict, and Warnings From History,' historian Odd Arne Westad explores the chilling parallels between current geopolitics and the era preceding World War I. He identifies several modern flash points, such as the Korean Peninsula, the South China Sea, and the Middle East, that could potentially ignite a global conflict. Westad warns that the great-power competition of a century ago still lurks within today's international relations. He argues that the world appears almost resigned to war, driven by a Freudian return of repressed imperial ambitions on a civilizational scale.\n\nWhile some scholars argue that technological advancements have made war more manageable, Westad presents a radically different and darker nightmare. He notes a deeply held sense that great-power war is highly unlikely, leading to a dangerous refusal to reckon with the scale of potential destruction. The once ubiquitous existential terror of nuclear weapons has largely dissipated from popular consciousness. Instead, people are increasingly conditioned to view modern warfare as a matter of precision, control, and localization through smart weaponry and artificial intelligence. However, Westad insists there is almost no evidence that increased destructive potential will make war impossible.\n\nThe notion that the immense force of war can be completely controlled is a persistent and dangerous fantasy. As the French philosopher Simone Weil observed while analyzing Homer's 'Iliad,' human ambition is inevitably swept away and blinded by the very force it imagines it can handle. 'The Coming Storm' serves to remind readers of the enormity of unleashed military power and the catastrophic consequences of miscalculation. By assessing how the great powers of a hundred years ago went so wrong, the book offers an antidote to the paralysis of imagination. It ultimately challenges leaders to break the cycle of history and avoid the next devastating conflagration."
}

for file_id, new_content in updates.items():
    path = f"/Users/go/my-github-project/app/public/data/articles/{file_id}.json"
    with open(path, "r") as f:
        data = json.load(f)
    data["content"] = new_content
    with open(path, "w") as f:
        json.dump(data, f, indent=2)

print("Updated 6 bad files.")
