import json

data = {
    "/Users/go/my-github-project/app/public/data/articles/restored_42d5e503.json": "During a scheduled Oval Office visit, an Atlantic editor experienced President Donald Trump's unique approach to media relations firsthand. Three hours before the meeting, Trump posted a provocative message on Truth Social, mocking the publication while simultaneously announcing the interview. When asked about the post, Trump explained that it was a strategic move to put pressure on the journalists while acknowledging a certain level of respect for their platform. He proudly admitted that he writes his social media posts himself, emphasizing how quickly he can dictate and publish them directly to his massive audience. However, this casual approach to communication severely contrasts with the strict protocols required for national security.\n\nIn a seemingly unrelated but equally controversial incident, Secretary of Defense Pete Hegseth faced intense scrutiny over his own communications. A Pentagon report revealed that Hegseth had sent highly sensitive operational information over an unapproved, unsecure network. This included identifying the quantity and strike times of U.S. aircraft heading into hostile territory hours before the mission's execution. If adversaries had intercepted these messages, they could have countered U.S. forces or repositioned their assets, potentially harming American pilots. Although the report noted the serious risk to operational security, Hegseth was not technically found in violation of secrecy rules because he possesses 'original classification authority.'\n\nHegseth quickly claimed total exoneration, brushing off the incident on social media as a closed case. Yet, critics pointed out his glaring hypocrisy, noting that he had fiercely condemned others for similar communication breaches in the past. During the 2016 election, Hegseth publicly questioned how America could build alliances if leaders recklessly mishandled sensitive information. The Department of Defense employs nearly three million people who are all subject to strict regulations regarding their behavior and communication. Any regular employee would face severe consequences for announcing military strikes on an insecure app, highlighting a troubling double standard at the highest levels.",

    "/Users/go/my-github-project/app/public/data/articles/restored_4ade7b09.json": "Financial publications frequently provide comprehensive listings of the top open-end mutual funds ranked by total assets. These funds diligently value their expansive portfolios on a daily basis to ensure accurate reporting for investors. They calculate and report their net asset values to the National Association of Securities Dealers by dividing the total dollar amount of their holdings by the number of outstanding shares. When evaluating these funds, total return figures reflect both market price changes and any issued dividends. To provide a standardized metric, these return calculations assume that all financial distributions are immediately reinvested back into the fund itself.\n\nBecause analytical firms like Lipper are constantly updating their vast databases, recently published returns may occasionally differ from previously calculated figures. It is important for investors to note that three-year returns are typically presented as cumulative values over that period. Additionally, the listed Net Asset Value (NAV) always represents the last reported closing price for the respective trading week. To help readers navigate the complex data, publications include a detailed footnotes section explaining various abbreviations and financial conditions. These footnotes clarify everything from missing performance data to specific fee structures, ensuring that investors can make fully informed financial decisions.",

    "/Users/go/my-github-project/app/public/data/articles/restored_503ef359.json": "Teyana Taylor has rapidly emerged as a multifaceted creative powerhouse, seamlessly balancing acting, music, and motherhood. In her acclaimed role as Perfidia Beverly Hills in the film 'One Battle,' she shared the screen with heavy hitters like Leonardo DiCaprio and Sean Penn. Despite having only twenty minutes of screen time, Taylor imbued her performance with so much pop and zeal that she completely stole the show. Her character's storyline deeply resonated with many women, touching on the isolating postpartum experiences of not feeling heard, seen, or beautiful. When Perfidia abandons her family to continue her activism, Taylor argues that villainizing her completely misses the point about the immense pressures placed on modern mothers.\n\nIn reality, women are frequently forced to be supermoms and superwives, rarely receiving any grace when they finally need a break. Like her complex character, Taylor knows exactly who she is and refuses to be boxed into a single career path. When she walked away from the music industry in 2020 due to feeling underappreciated, many critics told her it was a foolish mistake. However, she boldly declared her intentions to become a great actress and an eventual director. Now, as an Oscar nominee, she feels no pressure, viewing the nomination itself as a massive victory that validates her undeniable talent.\n\nBeyond the glitz of awards season, Taylor understands that hard work must have personal meaning beyond mere accolades. She recently returned to music to create a new project because taking a break allowed her to fall back in love with the art form. Her journey through a highly public divorce and finding a new relationship provided her with raw, fresh material about love, heartbreak, and healing. Looking ahead, her ambitious schedule includes filming a new movie, launching a music tour, and finally graduating from culinary school. Confidently setting her sights on achieving an EGOT, Taylor firmly believes that true creatives should never be caged, but instead allowed to spread their wings entirely.",

    "/Users/go/my-github-project/app/public/data/articles/restored_50b3345d.json": "In 1912, Woodrow Wilson became the first Southerner to win the presidency after the Civil War by making bold promises to Black voters. He famously declared that African Americans could count on him for absolute fair dealing and assistance in advancing their racial interests. However, by the end of his term, it became painfully clear that Wilson's political promises would ring completely hollow. He packed his cabinet with white supremacists who systematically segregated the federal workforce while dismissing and demeaning Black employees. Furthermore, he hosted a White House screening of a film that glorified the Ku Klux Klan, directly co-signing violently racist imagery from the highest office in the nation.\n\nMore than a century later, historians draw distinct parallels between Wilson's abandonment of Black Americans and President Donald Trump's recent political actions. Critics note that Trump's efforts to gut the federal government and assail diversity policies closely mirror Wilson's destructive historical legacy. Despite Trump's claims that he has done more for Black people than any president since Abraham Lincoln, his rhetoric often contradicts his stated actions. For instance, he recently faced severe backlash for posting an AI-generated, racist video clip on his social media feed that dehumanized political opponents. Scholars argue that posting such dehumanizing imagery online is the modern equivalent of Wilson screening a racist film at the White House.\n\nInterestingly, both Wilson and Trump were initially buoyed in their election efforts by securing surprising surges of support from Black voters. In his recent inaugural address, Trump acknowledged this crucial voting bloc, promising that he had heard their voices during the campaign. Supporters of Trump argue that shrinking the government actually empowers the private sector, allowing minority communities to prosper independently without federal interference. Conversely, historians emphasize that the negative impacts of Wilson's covertly segregationist policies were felt for generations. Experts warn that allowing the presidency to elevate and normalize dehumanizing racial rhetoric could cause similar, long-lasting damage to the nation's social fabric today.",

    "/Users/go/my-github-project/app/public/data/articles/restored_511ef31b.json": "In the modern corporate landscape, true success at scale requires persuading a massive consumer base that a company consistently delivers the goods. Amazon perfectly understands this critical lesson, utilizing its massive reach to become the newly crowned leader of the Fortune 500. The e-commerce giant's ability to attract and effectively monetize the masses has become a virtually unstoppable economic force. Consequently, Amazon has finally toppled Walmart, ending the retail competitor's impressive thirteen-year streak atop the ranking of largest U.S. companies by revenue. Furthermore, Amazon delivered record-breaking profits this year, largely driven by the explosive growth of its highly popular AWS cloud computing business.\n\nThe broader business world remains engaged in an eternal battle to keep demanding customers fully satisfied and loyal. For example, tech behemoth Microsoft is currently scrambling to secure the fierce loyalty of new artificial intelligence users. Similarly, financial institutions like American Express had to completely reimagine their traditional credit card perks to guide customers through the global pandemic. However, even the most customer-obsessed companies inevitably stumble and face significant public relations challenges from time to time. Ultimately, the true test of corporate resilience is how fallen industry giants manage to regain consumer trust after making highly publicized mistakes."
}

for path, new_content in data.items():
    with open(path, 'r') as f:
        d = json.load(f)
    d['content'] = new_content
    with open(path, 'w') as f:
        json.dump(d, f, indent=2)

print("Batch 3 updated successfully.")
