import json

data = {
    "/Users/go/my-github-project/app/public/data/articles/restored_15a533d1.json": "Since becoming McKinsey & Company's global managing partner in 2021, Bob Sternfels has navigated a series of thorny challenges. He has taken significant steps to restore the consulting firm's reputation following several scandals, most notably its role in the U.S. opioid crisis. To achieve this, he has worked to tighten the rules on client selection and governance without alienating the firm's partners. Additionally, to prepare McKinsey for the AI era, he is driving a major organizational transformation. This shift focuses less on traditional consulting services and more on delivering tangible, technology-driven outcomes.\n\nIn a recent interview reflecting on McKinsey's centennial, Sternfels noted that the half-life of companies is getting shorter as technological change quickens. He described this milestone as an opportunity to examine the firm's history and determine how it needs to adapt in an unpredictable world. While much attention is given to the technology itself, Sternfels emphasized that the real secret to success lies in organizational change. Companies must figure out how work looks after AI is implemented and whether a flatter organization can increase efficiency. When organizations successfully align these structural changes, business leaders like the CFO and CIO finally get on the same page.\n\nDespite the promise of AI, Sternfels acknowledged that full integration is taking longer than many people initially anticipated. Internally, McKinsey is actively discussing how artificial intelligence will fundamentally shift the economics of the consulting industry. These conversations revolve around the potential impacts on overall headcount, service pricing, workforce productivity, and long-term profit margins. By successfully navigating these complex internal discussions, McKinsey hopes to set a strong precedent for its clients. Ultimately, the firm aims to prove that mastering AI-driven organizational design will be the key to surviving the next century of business.",

    "/Users/go/my-github-project/app/public/data/articles/restored_18534720.json": "Metaphors for the troubled trans-Atlantic relationship abound, describing it as a marriage, a divorce, or a parent and child navigating an empty nest. All these comparisons highlight a shared reality: the dynamic between the United States and Europe is morphing into something entirely new. It has become increasingly clear that the world is not returning to the post-Cold War status quo. However, too much of the debate continues to focus on limiting this transition and fretting over worst-case scenarios. Policymakers on both sides seem reluctant to explore what a healthy, reconfigured relationship should actually look like.\n\nInstead of dreading change, leaders must smooth out the erratic seesaw of partisan approaches to European diplomacy. The constant flip-flopping between U.S. administrations creates bad feelings and the impression that America is an unreliable partner. Rather than promising a return to past dominance, politicians should imagine a robust, friendly relationship based on equality. Different administrations must also decide whether they want a cultural war with Europe or a reliable defense partner. Choosing conflict will only breed acrimony that ultimately undermines critical international security efforts.\n\nMoving forward, policymakers must recognize shared interests rather than assuming U.S. influence in Europe is limitless. Both sides benefit from resisting Chinese global hegemony, sustaining European stability, and ensuring mutual economic growth. Treating European nations as equal partners, rather than dependencies, perfectly describes a highly functional trans-Atlantic relationship. There is no inherent contradiction between America's commitment to NATO and the idea that Europe should primarily defend itself. As Dwight D. Eisenhower noted in 1951, Western Europe cannot rely exclusively on American units to guard its far frontiers forever.",

    "/Users/go/my-github-project/app/public/data/articles/restored_1feb64db.json": "The latest edition of the men's T20 cricket World Cup opened with a stark display of South Asia's complex geopolitical rivalries. While India hosted traditional matches, its tense relationship with neighboring nations overshadowed the tournament's sporting spirit. Countries like Pakistan and Bangladesh, frustrated by what they perceive as India's domineering influence, pushed back through boycotts and scheduling protests. The resulting friction reduced a global sporting event into a highly politicized stage for regional pathologies. Rather than unifying the continent, the tournament highlighted how sports often serve as geopolitics by other means.\n\nTensions escalated dramatically when the Indian Premier League forced a Kolkata-based team to drop a newly purchased Bangladeshi player. This decision followed immense pressure from out-of-work political figures and members of India's ruling Bharatiya Janata Party. Relations between India and Bangladesh had already been deteriorating since Bangladesh's autocratic prime minister fled to India amid massive protests. Enraged by India's actions, Bangladesh unsuccessfully petitioned the International Cricket Council to move its World Cup matches to Sri Lanka. Ultimately, Bangladesh was excluded from the contest and replaced by Scotland, deepening regional resentments.\n\nMeanwhile, Pakistan also wielded cricket as a political weapon by initially banning its national team from playing against India. Following a short, contentious border skirmish, Pakistan sought to harm its bigger neighbor financially by boycotting the highly lucrative match. Since India-Pakistan matches draw massive audiences and generate significant advertising revenue, the boycott hit the Indian cricket establishment where it hurt. Although backchannel negotiations eventually saved the scheduled match, the brinkmanship dragged cricket ever deeper into political dysfunction. Ultimately, while the sport's rules logically pursue victory, South Asian geopolitics remains an increasingly negative-sum game.",

    "/Users/go/my-github-project/app/public/data/articles/restored_2767a31a.json": "For anyone looking for signs of spring, there were plenty to be found at the recently concluded Milan Fashion Week. The highly anticipated shows took place beneath sunny blue skies and drew crowds dressed in exceptionally bright clothing. Attendees enthusiastically sported chest-bearing tops and sunglasses of all shapes and sizes, making winter coats seem like a distant memory on the streets. However, notable coats did make an appearance on the runways, serving as a striking contrast to the warm weather outside. At the Bottega Veneta show, outerwear featured big, shaggy, and leathery designs that captivated the audience.\n\nMeanwhile, the Jil Sander show presented outerwear that was distinctly understated but equally memorable. Another surprising trend emerged on the Diesel runway, where models paired high-cut bikini bottoms with cozy sweaters and casual shirts. Major fashion houses, including Marni and Prada, heavily featured attire in vibrant shades of pink. This bold color, along with springy yellows and bright greens, was also highly prevalent among the fashionable street crowds. Dior impressed attendees with innovative materials, showcasing trompe l’oeil Donegal tweeds that were actually made of airy, lightweight jersey.\n\nClassic fashion staples also received significant attention during the exciting week of runway presentations. Dior showcased a modern take on its iconic mini Bar jacket, pairing it with a playful mini-crini and denim jeans. Similarly, Saint Laurent focused heavily on its foundational Le Smoking tuxedo jacket, a historic garment that defined the brand. Because this year marks the 60th anniversary of Le Smoking, the designer understandably celebrated it through numerous creative iterations. Ultimately, Milan Fashion Week successfully blended bold new spring trends with masterful tributes to legendary fashion history.",

    "/Users/go/my-github-project/app/public/data/articles/restored_36c3bca3.json": "On a Thursday evening in September, I excused myself from the family dinner table to begin a journalistic experiment. I had promised my bishop that my foray into sports betting would not lead down a slippery slope. Fifteen minutes before a football kickoff, I scrolled through the available wagers on a betting app in wide-eyed bewilderment. Historically, gambling was relegated to the shadowy corners of society, controlled by offshore bookies and criminals. Professional sports leagues had long remained determined to keep this illicit activity at a safe distance from their games.\n\nHowever, modern legal betting apps transformed me into an excited kid at a carnival, impulsively throwing money at random attractions. I foolishly placed live bets on whatever game ESPN happened to be broadcasting, completely ignoring essential research. On one disastrous Saturday afternoon, I repeatedly lost money chasing bad bets during a random college football game. By the end of my first chaotic week, I had won only three out of fourteen total wagers. Seeking professional insight, I shared my betting slips with statistical expert Nate Silver, who audibly laughed at my terrible strategy.\n\nSilver gently informed me that I was making classic mistakes typical of a highly uninformed, recreational bettor. He explained the harsh realities of the sports-betting economy, noting that bookmakers essentially charge a fee for every placed bet. Consequently, a gambler must win at least 52.5 percent of their wagers just to break even financially. My most obvious mistake was relying exclusively on a single platform instead of shopping for better odds across multiple sportsbooks. Furthermore, he advised me to avoid highly volatile proposition bets on individual players and risky, multi-leg parlays."
}

for path, new_content in data.items():
    with open(path, 'r') as f:
        d = json.load(f)
    d['content'] = new_content
    with open(path, 'w') as f:
        json.dump(d, f, indent=2)

print("Batch 2 updated successfully.")
