import json

data = {
    "/Users/go/my-github-project/app/public/data/articles/restored_02bf7515.json": "Election officials emphasize the need for flexible federal funding to ensure smooth elections. Kentucky Secretary of State Michael Adams noted that running federal, state, and local elections simultaneously requires modernization. This modernization is best supported when Congress provides unconditional funding. During the COVID-19 pandemic, funding from HAVA grants and the CARES Act played a critical role in helping Kentucky adapt to unprecedented challenges. For example, Adams implemented excuse-free absentee voting and three weeks of open polls, resulting in the highest primary turnout since 2008.\n\nHe later worked with Democratic Governor Andy Beshear to make some of these changes permanent, despite opposition from within his own party. For his efforts, Adams was awarded the John F. Kennedy Profile in Courage in 2024. He emphasized that voting should be as nonpartisan as renewing a driver's license. Meanwhile, the Republican National Committee (RNC) faces a different challenge: restoring trust among voters who remain highly skeptical of the election system. The RNC has invested millions of dollars in a litigation machine that aims to change voting rules under the banner of election integrity.\n\nHowever, critics argue these legal efforts are designed to make it harder to vote and easier to undermine election results. If the Supreme Court adopts the RNC's legal theories, hundreds of thousands of eligible Americans could be disenfranchised due to postal delays beyond their control. Despite these legal pushes, it remains uncertain whether such rulings will effectively restore voter faith in elections. Republicans see these efforts as necessary to make the system more acceptable to their base. Conversely, some experts warn that Supreme Court rulings might make voting more confusing, further suppressing turnout.\n\nSkeptics point out that many of these legal battles focus on issues with relatively small impacts. Ultimately, only time will tell if the RNC's substantial investments in election integrity litigation will influence voter trust or inadvertently complicate the voting process.",

    "/Users/go/my-github-project/app/public/data/articles/restored_02cb8c60.json": "Dozens of members of the Pussy Riot, an anti-Putin feminist protest group, recently stormed Russia's exhibition space at the Venice Biennale. They were joined by the Ukrainian feminist group FEMEN, who dramatically filled the venue with blue and yellow smoke. However, some observers view these protests as the last stand of a losing argument, as Russia slowly begins to reintegrate into global spheres. Institutions that once firmly shut their doors to Russian participation appear to be gradually holding them open once again. The Venice Biennale serves as the most visible sign of this cultural shift.\n\nIf Venice represents the cultural test case, the sporting world is where the most significant shift will be decided. Political scientist Jules Boykoff noted that Russia is highly likely to participate in the upcoming 2028 Olympic Games in Los Angeles. Recent international events, including hints from International Olympic Committee officials, suggest a growing willingness to welcome Russian athletes back to the world stage. Ultimately, this gradual acceptance in both art and sports indicates a complex and controversial return for Russia in the international community.",

    "/Users/go/my-github-project/app/public/data/articles/restored_092f07e4.json": "The upcoming election will be the first opportunity for Israelis to have a direct say on their government since the devastating attacks on October 7, 2023. Prime Minister Benjamin Netanyahu astonished both political enemies and allies by maintaining his grip on power following the bloodiest day in Israel's history. Despite holding a fractious coalition together, opinion polls have consistently shown that his support remains stubbornly below the levels needed to secure his re-election. Critics argue that Netanyahu's political conduct has been increasingly driven by his desire for personal survival as a defendant in ongoing legal cases. Consequently, there are legitimate concerns that his political calculations may sometimes outweigh Israel's broader national security interests.\n\nFurthermore, international scrutiny has intensified over Israel's foreign policy decisions. Some prominent American political figures claim that these decisions are being unduly influenced by powerful lobbying efforts. Experts warn that if such sentiments gain broader traction, it could severely damage Israel's most crucial diplomatic relationship with the United States. Even if Netanyahu initiated military campaigns with an eye on the ballot box, these actions have not translated into the expected political boost. Public opinion researchers note that there has been no significant, long-lasting rally of trust in the government.\n\nInstead, any minor increase in support quickly declined back to prewar levels. This leaves Netanyahu's political future highly uncertain as the election approaches. The challenge for the Israeli public will be navigating the complex balance between national security demands and political accountability. Ultimately, the results of the upcoming election will serve as a crucial barometer of the nation's priorities in the aftermath of a historic tragedy.",

    "/Users/go/my-github-project/app/public/data/articles/restored_0eaefa8f.json": "Major sports leagues initially opposed legalized sports betting, but they eventually embraced it to reverse declining TV ratings and attract younger fans. Before long, however, these organizations found themselves financially beholden to the gambling industry they helped create. Today, the NFL, NBA, and MLB all hold significant equity stakes in the data companies that power sportsbooks. They even license broadcast rights directly to streaming services operated by betting platforms, often rushing to defend their gambling partners during game-fixing scandals. This growing integration has fundamentally changed how fans interact with the games, sometimes bringing out a disconcerting and primal intensity.\n\nFor many bettors, a seemingly guaranteed win can vanish in an instant due to a single overturned play or fumble. When money vaporizes on an unexpected loss, gamblers often experience intense, irrational anger directed at players they have never met. This emotional volatility is becoming alarmingly common, as the normalization of betting has coincided with a sharp increase in athlete harassment. More than a third of Division I men's college basketball players report receiving abusive messages directly from disgruntled gamblers. In the adrenaline spike of a tough loss, bettors frequently lose perspective and treat athletes as mere variables in their personal financial dramas.\n\nThis disturbing trend is particularly severe in individual sports like tennis, where the frustration of losing bettors lands squarely on solitary competitors. When athletes underperform, they are no longer just letting down their fans, but actively costing gamblers significant amounts of money. Some players have shared baffling experiences of receiving vicious online abuse from seemingly normal individuals with wholesome social media profiles. It highlights a dark psychological shift where the stakes of a wager completely override basic human empathy. Ultimately, the rapid expansion of legalized sports betting forces society to grapple with the increasingly toxic environment it creates for athletes.",

    "/Users/go/my-github-project/app/public/data/articles/restored_0f34592b.json": "The United States has long dismissed the Chinese system as being too rigid to foster true frontier innovation. The American democratic and capitalist model has undeniably produced a dazzling lineup of transformative technological breakthroughs over the years. However, while the U.S. cannot and should not replicate China's approach, it must find its own way to compete on a broader global playing field. Americans need to focus not only on innovating but also on producing advanced technology and controlling vital supply chain inputs. To achieve this, an effective American technology strategy must establish and protect enduring structural advantages that deliver concrete results.\n\nFirst, the United States must revitalize its techno-industrial base to preserve its position at the cutting edge of global innovation. This requires generating enough domestic capacity to produce advanced technologies at scale across diversified and resilient supply chains. Simultaneously, the U.S. military must prioritize rapid adaptation, which is critical for deterring aggression and maintaining peace in vulnerable regions. Washington should also work to build a democratic digital order that establishes American technology as the prevailing global model. This model should be protected by high safety standards, financed transparently, and deeply rooted in respect for human rights and data privacy.\n\nFinally, the United States must establish a baseline of stability in its relationship with China to prevent a destructive race to the bottom. Meaningful cooperation between the two technological superpowers is essential for addressing shared global challenges. These strategic goals are mutually reinforcing, as a strong industrial base directly supports both military power and economic security. By adopting this comprehensive approach, America can maintain its technological leadership without compromising its core democratic values. Ultimately, securing these high grounds will ensure that technological policy positively impacts the real lives of the American people."
}

for path, new_content in data.items():
    with open(path, 'r') as f:
        d = json.load(f)
    d['content'] = new_content
    with open(path, 'w') as f:
        json.dump(d, f, indent=2)

print("Batch 1 updated successfully.")
