import json

data_replacements = {
    "/Users/go/my-github-project/app/public/data/articles/restored_deep_21a566e0.json": """Scrutinize a receipt from any recent purchase, and it might be hard to avoid feeling you got swindled. Since early 2020, the consumer price index has risen so quickly that everyday items have become noticeably more expensive. In some categories, including groceries, electricity, and car insurance, the price increases have been even steeper. Consequently, major retailers are seeing more affluent customers raid their aisles in search of cheaper products. While some price hikes are clearly linked to tariffs or shortages, many others seem inexplicably high to the average consumer.

When the online retailer Quince launched in 2019, the company couldn’t have anticipated the impending years of pricing chaos. However, this turbulent economic environment ultimately made for splendid timing for their specific business model. The San Francisco-based company specializes in selling its own brand of low-cost luxury goods. They offer items designed to lessen the tension between consumer aspirations and tightening budgets. Quince promises to cut out the middlemen, enabling it to sell high-quality goods at significantly lower prices.

Over the past few years, Quince has expanded into a surprising variety of other premium product categories. They now offer everything from American-made sofas and fine jewelry to fragrances and nutritional supplements. The company has built a highly efficient system predicated on sweeping data analysis and close relationships with manufacturers. These advantages have enabled the retailer to enter new product categories far more quickly than traditional models allow. Recently, Quince has gone even further by selling third-party products from recognized high-end brands to boost its overall luxury aura.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_2236b68d.json": """Every year, the National Association for Business Resources announces the 'Best and Brightest Companies to Work For in the Nation.' This prestigious initiative highlights organizations that demonstrate exceptional commitment to their employees and workplace culture. The list features a diverse array of companies spanning multiple industries, including healthcare, finance, engineering, and technology. Notable organizations consistently recognized include major healthcare providers, regional credit unions, and leading energy companies. The featured companies range from well-known national corporations to highly specialized regional firms from across the country.

Recognizing these top-tier companies encourages others to improve their own workplaces and prioritize employee satisfaction. The initiative provides a benchmark for evaluating organizational culture, employee engagement, and overall corporate health. Organizations that make the list often showcase innovative human resources practices and strong employee retention strategies. By publicly celebrating these elite leaders, the association promotes a broader standard of excellence in the business world. Ultimately, these awards help job seekers identify companies that truly value and invest in their workforce.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_22c94e65.json": """When Tasha Kozak, a school social worker, met a family living in their car, she immediately stepped in to help. After several months of consistent support, she helped them find stable housing and witnessed the children's grades improve. Moments like that are exactly why Kozak remains deeply passionate about her career in social work. She believes that the majority of effective social work relies heavily on human connection and relationship building. However, like many in her underpaid profession, Kozak found herself looking for ways to supplement her income.

During her summer break, Kozak discovered a gig-work platform called Mercor that recruits experts to train artificial intelligence. She was interviewed by an AI agent that asked probing, detailed questions, much like a human supervisor would. Soon, she was earning as much money training AI part-time as she did working full-time with actual families. Her task involved writing specific prompts for an AI model to generate social developmental histories based on fictitious case files. Kozak is now part of a large, segmented team of contractors actively translating their professional judgment into AI training data.

Across the country, many other skilled professionals are performing similar tasks for the tech industry. Doctors, novelists, and investment bankers are spending their off-hours evaluating and refining AI-generated content in their respective fields. Mercor has successfully built a massive workforce of tens of thousands of specialized experts using this exact model. In just three years, the startup has raised hundreds of millions in venture capital and achieved a massive valuation. The company argues that feeding models high-quality, expert-driven training data is crucial for making AI truly economically useful.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_23746c68.json": """The sport of cricket has increasingly become entangled in the complex geopolitics of South Asia. Like all teams except England and Australia, the Pakistan cricket board heavily relies on funding from the International Cricket Council. However, its government recently calculated that upsetting India’s political establishment was worth potential financial and sporting losses. This tension is exacerbated by the fact that India’s powerful cricket board acts almost as a wing of the ruling political party. Consequently, the leadership of these national cricket boards is deeply tied to their respective government ministries.

Observers seeking to understand South Asia’s dysfunctional international relationships could easily be overwhelmed by the region's historical grievances. Decades of wars, coups, and terrorism are superimposed upon centuries of deep-seated religious and linguistic divides. For many onlookers, observing the dynamics of international cricket provides a clearer lens into these geopolitical realities. While the rules of the sport pursue a clear victory, the regional geopolitics often resemble a negative-sum game. Ultimately, the intense rivalries played out on the cricket pitch perfectly mirror the broader diplomatic brinkmanship between these nations.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_243cc6dc.json": """The recently appointed CEO of Red Lobster, Damola Adamolekun, faces an immense challenge in reviving the iconic American restaurant chain. Backed by the investment firm Fortress, Adamolekun was hired to execute a comprehensive turnaround plan for the struggling business. However, a major obstacle to profitability remains the company's incredibly high lease costs across hundreds of locations. During bankruptcy proceedings, Red Lobster was largely prevented from canceling leases for its chronically unprofitable restaurants. Without a viable way to renegotiate or exit these burdensome leases, the chain continues to burn through cash.

Fortress and its partners currently hold the keys to Red Lobster’s survival, but their willingness to invest further remains uncertain. The chain has already burned through much of its post-bankruptcy capital and requires tens of millions more to stay afloat. Recent internal changes at Fortress suggest the firm might be reevaluating its restaurant portfolio and tightening its purse strings. Simultaneously, Red Lobster has experienced significant turnover in its executive team, raising questions about internal stability. The company's future now heavily depends on Adamolekun proving that the business is genuinely worth saving.

Neither the shifting dynamics at Fortress nor the executive turnover at Red Lobster seem particularly promising for the chain. The owners lack easy options and may have to resort to another bankruptcy or sell the chain in parts. While a failure wouldn't devastate Fortress financially, it would severely damage their reputation for reviving beloved brands. Some competitors, like Chili’s, have successfully pulled off dramatic turnarounds using targeted marketing and menu adjustments. Adamolekun remains optimistic, hoping that remodeling efforts and strategic improvements will eventually restore the brand to profitability."""
}

for filepath, new_content in data_replacements.items():
    with open(filepath, 'r') as f:
        data = json.load(f)
    data['content'] = new_content
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)

print("Batch 3 successfully replaced.")
