import json

data_replacements = {
    "/Users/go/my-github-project/app/public/data/articles/restored_deep_27443fd0.json": """Recent economic policies in the United Kingdom have sparked significant debate regarding their long-term impact on the nation's growth. The most damaging, self-harming economic policies were arguably implemented during the Brexit transition, which cost the country a noticeable percentage of its GDP. Furthermore, the short-lived 'Growth Plan' introduced in 2022 included billions in unfunded tax cuts that caused severe turmoil in financial markets. This ambitious but flawed strategy led to a historic crash of the pound and resulted in the shortest prime ministerial tenure in British history. The country is still recovering from these shocks, as well as from earlier cuts to capital infrastructure during the austerity era.

Despite these profound challenges, some economists maintain that the U.K. is not uniquely disadvantaged compared to its peers. The nation shares similar inflation and productivity challenges with other advanced economies across Europe and North America. However, Britain possesses many enduring structural strengths that could potentially put it in a good position for future recovery. It retains a highly educated workforce, world-class universities, and a robust technology and services sector. Ultimately, navigating out of this economic slump will require political stability and a renewed focus on sustainable, long-term investments rather than quick fixes.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_27c1791f.json": """China recently celebrated a highly successful year of exploration and shipping in the Arctic region. A Chinese ice-breaking ship completed the country’s largest ever Arctic expedition, which included a crewed deep-sea dive beneath the ice. Additionally, a Chinese-operated container ship finished the first scheduled transit from China to Europe via the Arctic without using icebreakers. Chinese media enthusiastically hailed this twenty-day voyage on the Northern Sea Route as the fastest delivery in the history of container shipping. Despite these milestones, the mood among China’s Arctic researchers has become noticeably subdued during recent international conferences.

This sudden modesty about China's Arctic ambitions stems from a dizzying shift in the region’s overall geopolitics. Chinese activities in the high north are increasingly viewed with suspicion by America, Canada, and various European nations. This apprehension is largely driven by China’s close strategic alignment with Russia, which controls significant portions of the Arctic coastline. Some Western officials fear that China is gathering crucial data and experience to operate navy ships and submarines in these icy waters. Consequently, Nordic countries that once hoped to preserve the Arctic as a zone of peaceful cooperation have started to prioritize regional security.

In response to these growing concerns, China has attempted to downplay the security-related aspects of its Arctic plans. The government now primarily presents itself as a transparent partner focused on climate-change research and environmental protection. Chinese representatives have publicly stated their readiness to strengthen open scientific collaboration with Nordic partners and other Arctic stakeholders. Furthermore, Chinese think-tanks accuse Western countries of unnecessarily over-securitizing their purely civilian maritime activities. However, until China reevaluates its strategic ties with Russia, its outreach to other Arctic states will likely continue to meet an icy response.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_28c7823f.json": """The Islamic Republic of Iran has long sought to centralize decision-making over all aspects of governance, society, and foreign policy. This grandiose ambition often appears to be an act of overreach, especially given the gaping divide between the regime's goals and the aspirations of its people. Still, the current regime has repeatedly demonstrated remarkable endurance, resilience, and a determination to preserve its power by any means necessary. These qualities may occasionally allow Iran to snatch a strategic, albeit costly, victory from the jaws of apparent defeat. By surviving intense pressure, the regime manages to deal a historic blow to the international order that Western nations have sought to sustain.

Iran's approach to asymmetric warfare relies heavily on decentralization and an ability to control the tempo of regional conflicts. Following targeted military strikes by its adversaries, Tehran rapidly launched counterattacks on maritime traffic in crucial global waterways like the Strait of Hormuz. Almost overnight, commercial traffic was severely curtailed, pushing up the worldwide price of oil, petrochemicals, and other key commodities. Instead of the rapid regime collapse that some anticipated, a costly war of attrition emerged. These conditions have allowed Iran to largely dictate when and how the broader regional conflict might eventually end.

This high-risk strategy is intended to force a lasting improvement in Tehran’s economic and regional sway. Iranian leaders have made it clear that any future regional cooperation must be predicated on the submission of its rivals. It may be tempting for Western analysts to dismiss this rhetoric as the death knell of an overly ideological regime. However, the regime’s perseverance in the face of crushing economic and military pressure recalls the intense fervor that sustained the state during its revolutionary beginnings. Ultimately, recognizing Iran's capacity for disruption is crucial for understanding the evolving balance of power in the Middle East.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_28e38d0c.json": """The ongoing military conflict in the Middle East has increasingly blurred the lines between national security and domestic political survival. Israeli Prime Minister Benjamin Netanyahu astonished both political enemies and allies by holding onto power after the bloodiest day in his nation's history. Despite maintaining a fractious coalition, opinion polls showed that public support for his leadership remained stubbornly low for years. Consequently, many analysts suspect that Netanyahu's recent political conduct has been heavily driven by his desire for personal political survival. There are legitimate concerns that, at times, his immediate political considerations may outweigh the country's long-term national security interests.

This dynamic is particularly evident in the escalating tensions and military exchanges with Iran and its regional proxies. Some high-profile critics argue that the war was expanded due to internal political pressure rather than imminent external threats. If this sentiment gains broader traction globally, it could severely damage Israel's most important diplomatic relationships. Furthermore, despite the aggressive military campaign, the expected domestic political boost for the ruling coalition has not materialized. Public opinion researchers note that there has been no significant rally in trust for the government, with approval ratings quickly declining to prewar levels.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_29130e7e.json": """The rapid advancement of artificial intelligence is triggering an unprecedented surge in global energy consumption. In southwest Memphis, a massive industrial megaproject known as Colossus is currently being constructed by Elon Musk's AI company, xAI. This sprawling data center, housed in a hangar larger than a dozen football fields, serves as a primary training ground for advanced generative AI models. The sheer scale of the facility is evident from the surrounding forest of new electrical towers and the heavy presence of construction equipment. To power such monumental computing efforts, tech companies are increasingly seeking vast and uninterrupted sources of electricity.

Industry experts project that data centers will soon consume more electricity than all of the country’s heavy industries combined. Roughly half of this massive power demand will come from facilities specifically equipped for the unique needs of generative AI programs. These advanced systems require constant, immense computational power to process text, generate images, and solve complex mathematical problems. Consequently, many energy and tech companies are reluctantly turning back to fossil fuels, viewing them as more reliable than current renewable options. This growing reliance on traditional power plants highlights the deep environmental tension inherent in the current artificial intelligence boom.""",

    "/Users/go/my-github-project/app/public/data/articles/restored_deep_29ad832b.json": """When Stephen Squeri took charge of American Express in 2018, he immediately pledged a 'revenue first' approach that prioritized top-line expansion. He significantly ramped up the marketing budget to attract a younger, more affluent demographic to the brand's premium cards. Platinum cardholders received new lifestyle benefits, and the company heavily invested in expanding its exclusive airport lounge network. Furthermore, Squeri oversaw the strategic purchase of the restaurant reservation platform Resy to integrate highly sought-after dining perks. Despite these successful updates, the company's core product remained fundamentally tethered to a wide menu of travel benefits.

This travel-heavy strategy faced a dire scenario when the global COVID-19 pandemic struck and effectively halted international movement. The company's premium products, which were rich in travel-focused benefits, literally became irrelevant overnight. While top management debated a hunkered-down, cost-flattening campaign that included widespread layoffs, Squeri boldly decided to play offense. He chose to invest heavily in customers by introducing temporary credits for streaming services and cell phone plans that were useful during lockdowns. He also adamantly refused to lay off any employees, believing that retaining trained staff was crucial for post-pandemic recovery.

This aggressive investment strategy initially risked generating an immense financial loss for the company during the crisis. However, Squeri secured the backing of major shareholders by arguing that protecting the brand's aura and customer loyalty was paramount. Ultimately, the new suite of stay-at-home benefits successfully prevented mass customer defections while government programs stabilized the broader economy. When the crisis lifted, Amex kept all the added perks and integrated even more lifestyle partnerships to boost the brand's everyday appeal. Today, the company's revenues have vastly exceeded pre-pandemic levels, proving that investing in customer value during a crisis can yield massive long-term dividends."""
}

for filepath, new_content in data_replacements.items():
    with open(filepath, 'r') as f:
        data = json.load(f)
    data['content'] = new_content
    with open(filepath, 'w') as f:
        json.dump(data, f, indent=2)

print("Batch 4 successfully replaced.")
